# Generated by Django 5.1.7 on 2025-03-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
