# Generated by Django 5.1.6 on 2025-03-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the product.', null=True)),
                ('sku', models.CharField(help_text='Unique stock keeping unit (SKU) for product identification.', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Number of items currently in stock.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently active and available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
