# Generated by Django 5.1.7 on 2025-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique stock keeping unit (SKU) for product identification.', max_length=100),
        ),
    ]
